# Generated by Django 4.0.6 on 2022-08-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('fwd', 'fwd'), ('mfd', 'mfd'), ('def', 'def'), ('gk', 'gk')], max_length=20)),
                ('age', models.IntegerField()),
                ('experience', models.CharField(choices=[('legend', 'legend'), ('superstar', 'superstar'), ('young', 'young'), ('prof', 'prof'), ('quick', 'quick'), ('strong', 'strong')], max_length=20)),
                ('date_buyed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Myteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[('fwd', 'fwd'), ('mfd', 'mfd'), ('def', 'def'), ('gk', 'gk')], max_length=20)),
                ('age', models.IntegerField()),
                ('experience', models.CharField(choices=[('legend', 'legend'), ('superstar', 'superstar'), ('young', 'young'), ('prof', 'prof'), ('quick', 'quick'), ('strong', 'strong')], max_length=20)),
                ('date_buyed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
