# Generated by Django 4.0.6 on 2022-08-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='skills',
            field=models.CharField(choices=[('💷💷💷💷💷💷💷💷💷💷💷💷💷', '💷💷💷💷💷💷💷💷💷💷💷💷💷'), ('💷💷💷💷💷💷💷💷💷💷💷💷', '💷💷💷💷💷💷💷💷💷💷💷💷'), ('💷💷💷💷💷💷💷💷💷💷💷', '💷💷💷💷💷💷💷💷💷💷💷'), ('💷💷💷💷💷💷💷💷💷💷', '💷💷💷💷💷💷💷💷💷💷'), ('💷💷💷💷💷💷💷💷💷', '💷💷💷💷💷💷💷💷💷'), ('💷💷💷💷💷💷💷💷', '💷💷💷💷💷💷💷💷'), ('💷💷💷💷💷💷💷', '💷💷💷💷💷💷💷'), ('💷💷💷💷💷💷', '💷💷💷💷💷💷'), ('💷💷💷💷💷', '💷💷💷💷💷'), ('💷💷💷💷', '💷💷💷💷'), ('💷💷💷', '💷💷💷'), ('💷💷', '💷💷'), ('💷', '💷')], default='💷', max_length=200),
        ),
        migrations.AddField(
            model_name='myteam',
            name='skills',
            field=models.CharField(choices=[('💷💷💷💷💷💷💷💷💷💷💷💷💷', '💷💷💷💷💷💷💷💷💷💷💷💷💷'), ('💷💷💷💷💷💷💷💷💷💷💷💷', '💷💷💷💷💷💷💷💷💷💷💷💷'), ('💷💷💷💷💷💷💷💷💷💷💷', '💷💷💷💷💷💷💷💷💷💷💷'), ('💷💷💷💷💷💷💷💷💷💷', '💷💷💷💷💷💷💷💷💷💷'), ('💷💷💷💷💷💷💷💷💷', '💷💷💷💷💷💷💷💷💷'), ('💷💷💷💷💷💷💷💷', '💷💷💷💷💷💷💷💷'), ('💷💷💷💷💷💷💷', '💷💷💷💷💷💷💷'), ('💷💷💷💷💷💷', '💷💷💷💷💷💷'), ('💷💷💷💷💷', '💷💷💷💷💷'), ('💷💷💷💷', '💷💷💷💷'), ('💷💷💷', '💷💷💷'), ('💷💷', '💷💷'), ('💷', '💷')], default='💷', max_length=200),
        ),
    ]
