# Generated by Django 4.0.6 on 2022-08-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_alter_market_options_alter_myteam_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='pstatus',
            field=models.CharField(choices=[('reserve', 'reserve'), ('onstart', 'onstart')], default='reserve', max_length=200),
        ),
        migrations.AddField(
            model_name='myteam',
            name='pstatus',
            field=models.CharField(choices=[('reserve', 'reserve'), ('onstart', 'onstart')], default='reserve', max_length=200),
        ),
    ]
