# Generated by Django 4.0.6 on 2022-08-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_market_pstatus_myteam_pstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myteam',
            options={'ordering': ['position', '-skills', '-pstatus']},
        ),
    ]
