# Generated by Django 4.0.6 on 2022-08-12 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0006_market_goals_myteam_goals_alter_myteam_skills_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='team',
        ),
        migrations.AddField(
            model_name='myteam',
            name='lteam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='myteam', to='transfer.league'),
        ),
    ]
