# Generated by Django 4.0.6 on 2022-08-12 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0007_remove_league_team_myteam_lteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myteam',
            name='lteam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='myteam', to='transfer.league'),
        ),
    ]
