# Generated by Django 4.0.6 on 2022-08-12 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0008_alter_myteam_lteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='theteams',
            fields=[
                ('myteam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transfer.myteam')),
                ('teamname', models.CharField(max_length=255)),
            ],
            bases=('transfer.myteam',),
        ),
    ]
