# Generated by Django 4.0.6 on 2022-08-12 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0010_alter_market_skills_alter_myteam_skills_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['position', '-skills', '-pstatus']},
        ),
        migrations.AddField(
            model_name='market',
            name='lteam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='market', to='transfer.league'),
        ),
    ]
