# Generated by Django 4.0.6 on 2022-08-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0011_alter_market_options_market_lteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='totalg',
            field=models.IntegerField(default=0),
        ),
    ]
